/** Keyword groups and rotation (hour UTC % 3). */
export const ROTATION = [
  ['Core Web Dev', 'Web Design', 'WordPress', 'Webflow/Framer'],
  ['AI/Vibe Coding', 'GoHighLevel', 'Adjacent Platforms', 'Modern Stack'],
  ['Ecommerce', 'Maintenance', 'Conversion/Performance'],
];

export const KEYWORDS = [
  { keyword: 'web development', group: 'Core Web Dev' },
  { keyword: 'website development', group: 'Core Web Dev' },
  { keyword: 'web developer', group: 'Core Web Dev' },
  { keyword: 'custom website', group: 'Core Web Dev' },
  { keyword: 'website builder', group: 'Core Web Dev' },
  { keyword: 'frontend developer', group: 'Core Web Dev' },
  { keyword: 'full stack developer', group: 'Core Web Dev' },
  { keyword: 'website project', group: 'Core Web Dev' },
  { keyword: 'web design', group: 'Web Design' },
  { keyword: 'website design', group: 'Web Design' },
  { keyword: 'website redesign', group: 'Web Design' },
  { keyword: 'landing page design', group: 'Web Design' },
  { keyword: 'UI UX website', group: 'Web Design' },
  { keyword: 'responsive web design', group: 'Web Design' },
  { keyword: 'homepage redesign', group: 'Web Design' },
  { keyword: 'one page website', group: 'Web Design' },
  { keyword: 'wordpress', group: 'WordPress' },
  { keyword: 'wordpress developer', group: 'WordPress' },
  { keyword: 'wordpress website', group: 'WordPress' },
  { keyword: 'wordpress development', group: 'WordPress' },
  { keyword: 'wordpress redesign', group: 'WordPress' },
  { keyword: 'wordpress customization', group: 'WordPress' },
  { keyword: 'wordpress migration', group: 'WordPress' },
  { keyword: 'wordpress speed optimization', group: 'WordPress' },
  { keyword: 'wordpress maintenance', group: 'WordPress' },
  { keyword: 'woocommerce', group: 'WordPress' },
  { keyword: 'elementor developer', group: 'WordPress' },
  { keyword: 'bricks builder', group: 'WordPress' },
  { keyword: 'headless wordpress', group: 'WordPress' },
  { keyword: 'webflow', group: 'Webflow/Framer' },
  { keyword: 'webflow developer', group: 'Webflow/Framer' },
  { keyword: 'webflow website', group: 'Webflow/Framer' },
  { keyword: 'webflow redesign', group: 'Webflow/Framer' },
  { keyword: 'figma to webflow', group: 'Webflow/Framer' },
  { keyword: 'webflow CMS', group: 'Webflow/Framer' },
  { keyword: 'framer', group: 'Webflow/Framer' },
  { keyword: 'framer developer', group: 'Webflow/Framer' },
  { keyword: 'framer website', group: 'Webflow/Framer' },
  { keyword: 'framer redesign', group: 'Webflow/Framer' },
  { keyword: 'figma to framer', group: 'Webflow/Framer' },
  { keyword: 'framer CMS', group: 'Webflow/Framer' },
  { keyword: 'AI website builder', group: 'AI/Vibe Coding' },
  { keyword: 'vibe coding', group: 'AI/Vibe Coding' },
  { keyword: 'AI web development', group: 'AI/Vibe Coding' },
  { keyword: 'AI web developer', group: 'AI/Vibe Coding' },
  { keyword: 'build website with AI', group: 'AI/Vibe Coding' },
  { keyword: 'claude code developer', group: 'AI/Vibe Coding' },
  { keyword: 'cursor AI developer', group: 'AI/Vibe Coding' },
  { keyword: 'lovable developer', group: 'AI/Vibe Coding' },
  { keyword: 'lovable app', group: 'AI/Vibe Coding' },
  { keyword: 'bolt developer', group: 'AI/Vibe Coding' },
  { keyword: 'bolt.new', group: 'AI/Vibe Coding' },
  { keyword: 'v0 developer', group: 'AI/Vibe Coding' },
  { keyword: 'v0 vercel', group: 'AI/Vibe Coding' },
  { keyword: 'replit developer', group: 'AI/Vibe Coding' },
  { keyword: 'supabase developer', group: 'AI/Vibe Coding' },
  { keyword: 'AI agent integration website', group: 'AI/Vibe Coding' },
  { keyword: 'chatbot website integration', group: 'AI/Vibe Coding' },
  { keyword: 'AI powered website', group: 'AI/Vibe Coding' },
  { keyword: 'gohighlevel', group: 'GoHighLevel' },
  { keyword: 'go high level', group: 'GoHighLevel' },
  { keyword: 'GHL', group: 'GoHighLevel' },
  { keyword: 'gohighlevel developer', group: 'GoHighLevel' },
  { keyword: 'gohighlevel website', group: 'GoHighLevel' },
  { keyword: 'gohighlevel funnel', group: 'GoHighLevel' },
  { keyword: 'gohighlevel automation', group: 'GoHighLevel' },
  { keyword: 'gohighlevel CRM', group: 'GoHighLevel' },
  { keyword: 'gohighlevel expert', group: 'GoHighLevel' },
  { keyword: 'shopify website', group: 'Adjacent Platforms' },
  { keyword: 'shopify developer', group: 'Adjacent Platforms' },
  { keyword: 'squarespace website', group: 'Adjacent Platforms' },
  { keyword: 'wix website', group: 'Adjacent Platforms' },
  { keyword: 'wix studio', group: 'Adjacent Platforms' },
  { keyword: 'bubble developer', group: 'Adjacent Platforms' },
  { keyword: 'react website', group: 'Adjacent Platforms' },
  { keyword: 'nextjs website', group: 'Modern Stack' },
  { keyword: 'nextjs developer', group: 'Modern Stack' },
  { keyword: 'next.js developer', group: 'Modern Stack' },
  { keyword: 'figma to nextjs', group: 'Modern Stack' },
  { keyword: 'figma to react', group: 'Modern Stack' },
  { keyword: 'tailwind css website', group: 'Modern Stack' },
  { keyword: 'astro website', group: 'Modern Stack' },
  { keyword: 'jamstack website', group: 'Modern Stack' },
  { keyword: 'sanity CMS', group: 'Modern Stack' },
  { keyword: 'ecommerce website', group: 'Ecommerce' },
  { keyword: 'ecommerce developer', group: 'Ecommerce' },
  { keyword: 'online store development', group: 'Ecommerce' },
  { keyword: 'woocommerce developer', group: 'Ecommerce' },
  { keyword: 'woocommerce store setup', group: 'Ecommerce' },
  { keyword: 'shopware', group: 'Ecommerce' },
  { keyword: 'shopware developer', group: 'Ecommerce' },
  { keyword: 'shopware 6', group: 'Ecommerce' },
  { keyword: 'product page optimization', group: 'Ecommerce' },
  { keyword: 'headless ecommerce', group: 'Ecommerce' },
  { keyword: 'website maintenance', group: 'Maintenance' },
  { keyword: 'website maintenance monthly', group: 'Maintenance' },
  { keyword: 'wordpress support retainer', group: 'Maintenance' },
  { keyword: 'website management ongoing', group: 'Maintenance' },
  { keyword: 'website support ongoing', group: 'Maintenance' },
  { keyword: 'webmaster ongoing', group: 'Maintenance' },
  { keyword: 'webflow maintenance', group: 'Maintenance' },
  { keyword: 'shopify maintenance', group: 'Maintenance' },
  { keyword: 'ongoing web developer', group: 'Maintenance' },
  { keyword: 'web development retainer', group: 'Maintenance' },
  { keyword: 'conversion rate optimization website', group: 'Conversion/Performance' },
  { keyword: 'conversion rate optimization', group: 'Conversion/Performance' },
  { keyword: 'landing page optimization', group: 'Conversion/Performance' },
  { keyword: 'core web vitals', group: 'Conversion/Performance' },
  { keyword: 'page speed optimization', group: 'Conversion/Performance' },
  { keyword: 'website speed optimization', group: 'Conversion/Performance' },
  { keyword: 'website audit', group: 'Conversion/Performance' },
  { keyword: 'technical SEO website', group: 'Conversion/Performance' },
];

export const PLATFORMS = [
  { name: 'WordPress', match: (k, job) => /wordpress/i.test(k) || job.skills?.some((s) => /wordpress/i.test(s)) || /wordpress/i.test(job.title) },
  { name: 'Elementor', keywords: ['elementor developer', 'elementor'] },
  { name: 'Bricks', keywords: ['bricks builder', 'bricks'] },
  { name: 'Webflow', keywords: ['webflow'] },
  { name: 'Framer', keywords: ['framer'] },
  { name: 'GoHighLevel', keywords: ['gohighlevel', 'go high level', 'GHL', 'highlevel'] },
  { name: 'Shopify', keywords: ['shopify'] },
  { name: 'WooCommerce', keywords: ['woocommerce'] },
  { name: 'Shopware', keywords: ['shopware'] },
  { name: 'Wix', keywords: ['wix'] },
  { name: 'Squarespace', keywords: ['squarespace'] },
  { name: 'Lovable', keywords: ['lovable'] },
  { name: 'Bolt', keywords: ['bolt.new', 'bolt developer', 'bolt'] },
  { name: 'v0', keywords: ['v0 developer', 'v0 vercel', 'v0'] },
  { name: 'Next.js', keywords: ['nextjs', 'next.js'] },
];

export function slotForHour(h) {
  return h % 3;
}

export function keywordsForSlot(slot) {
  const groups = ROTATION[slot];
  return KEYWORDS.filter((k) => groups.includes(k.group));
}
