#!/usr/bin/env python3
import json
from pathlib import Path

BASE = Path(__file__).parent
JOBS = BASE / "jobs.jsonl"

NEW = [
    {
        "url": "https://www.upwork.com/jobs/~022099325360985391240",
        "title": "Web Developer",
        "matchedKeyword": ["web development", "web developer", "webflow", "webflow developer", "wordpress"],
        "keywordGroup": "WEBFLOW / FRAMER",
        "postedAt": "2026-09-14T02:33:32.918Z",
        "type": "hourly",
        "budget": None,
        "budgetFixed": None,
        "rateHourlyMid": None,
        "duration": "1 to 3 months",
        "proposals": None,
        "clientCountry": "United States",
        "paymentVerified": True,
        "clientSpend": "$35,672.33",
        "clientSpendNum": 35672.33,
        "clientHireRate": None,
        "clientRating": 5.0,
        "experienceLevel": "expert",
        "skills": ["Web Development", "WordPress", "HTML", "Web Design"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099322731792748025",
        "title": "Figma UI/UX Designer – Improve E-commerce Checkout & Account (Desktop + Mobile)",
        "matchedKeyword": ["UI UX website", "landing page design", "website design", "web design"],
        "keywordGroup": "WEB DESIGN",
        "postedAt": "2026-09-14T02:22:46.077Z",
        "type": "fixed",
        "budget": "200.00",
        "budgetFixed": 200.0,
        "rateHourlyMid": None,
        "duration": "Less than 1 month",
        "proposals": None,
        "clientCountry": "India",
        "paymentVerified": True,
        "clientSpend": "$1,344.00",
        "clientSpendNum": 1344.0,
        "clientHireRate": None,
        "clientRating": None,
        "experienceLevel": "intermediate",
        "skills": ["UI/UX Prototyping", "UX & UI Design", "Figma Make"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099322348271353992",
        "title": "Set Up WaveApps for Invoice Payment",
        "matchedKeyword": ["wordpress development", "wordpress"],
        "keywordGroup": "WORDPRESS",
        "postedAt": "2026-09-14T02:22:13.783Z",
        "type": "hourly",
        "budget": "10.00–20.00/hr",
        "budgetFixed": None,
        "rateHourlyMid": 15.0,
        "duration": "Less than 1 month",
        "proposals": 5,
        "clientCountry": "CAN",
        "paymentVerified": True,
        "clientSpend": None,
        "clientSpendNum": None,
        "clientHireRate": None,
        "clientRating": None,
        "experienceLevel": "intermediate",
        "skills": ["PHP", "PayPal Integration", "Web Development", "WordPress"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099322763449314125",
        "title": "Chinese official website designer/developer",
        "matchedKeyword": ["custom website", "website development", "web development"],
        "keywordGroup": "CORE WEB DEVELOPMENT",
        "postedAt": "2026-09-14T02:22:46.043Z",
        "type": "fixed",
        "budget": "250.00",
        "budgetFixed": 250.0,
        "rateHourlyMid": None,
        "duration": "1 to 3 months",
        "proposals": None,
        "clientCountry": "SGP",
        "paymentVerified": True,
        "clientSpend": "$570.00",
        "clientSpendNum": 570.0,
        "clientHireRate": None,
        "clientRating": None,
        "experienceLevel": "expert",
        "skills": ["Custom Web Design", "Web Development", "WordPress"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099321488491990521",
        "title": "Build a Webflow website for an iOS app",
        "matchedKeyword": ["webflow", "webflow developer", "webflow website", "landing page design"],
        "keywordGroup": "WEBFLOW / FRAMER",
        "postedAt": "2026-09-14T02:18:12.208Z",
        "type": "fixed",
        "budget": "150.00",
        "budgetFixed": 150.0,
        "rateHourlyMid": None,
        "duration": "1 to 3 months",
        "proposals": 5,
        "clientCountry": "United States",
        "paymentVerified": True,
        "clientSpend": "$1,180.00",
        "clientSpendNum": 1180.0,
        "clientHireRate": None,
        "clientRating": 5.0,
        "experienceLevel": "entry_level",
        "skills": ["Webflow"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099321758453349741",
        "title": "Build Educational Product Website",
        "matchedKeyword": ["website development", "landing page design", "wordpress", "wordpress development"],
        "keywordGroup": "WORDPRESS",
        "postedAt": "2026-09-14T02:19:46.405Z",
        "type": "fixed",
        "budget": "2,100.00",
        "budgetFixed": 2100.0,
        "rateHourlyMid": None,
        "duration": "Less than 1 month",
        "proposals": 28,
        "clientCountry": "United States",
        "paymentVerified": True,
        "clientSpend": "$38,037.10",
        "clientSpendNum": 38037.1,
        "clientHireRate": None,
        "clientRating": 4.96,
        "experienceLevel": "entry_level",
        "skills": ["Landing Page Optimization", "WordPress Website Design", "Landing Page Design"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099319278920060409",
        "title": "WordPress Expert – Secure Existing Website,  Audit Speed & Fix Small Issues, ongoing maintenance",
        "matchedKeyword": ["wordpress maintenance", "wordpress developer", "website maintenance", "wordpress"],
        "keywordGroup": "MAINTENANCE / RETAINERS",
        "postedAt": "2026-09-14T02:09:43.280Z",
        "type": "hourly",
        "budget": "8.00–28.00/hr",
        "budgetFixed": None,
        "rateHourlyMid": 18.0,
        "duration": "3 to 6 months",
        "proposals": 26,
        "clientCountry": "USA",
        "paymentVerified": True,
        "clientSpend": "$305.74",
        "clientSpendNum": 305.74,
        "clientHireRate": None,
        "clientRating": None,
        "experienceLevel": "intermediate",
        "skills": ["WordPress Security", "WordPress Optimization", "WordPress Maintenance"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099318972589352541",
        "title": "Full Stack Developer (Next.js, Python, Django) for AI-Powered Web Applications",
        "matchedKeyword": ["full stack developer", "nextjs developer", "AI web development"],
        "keywordGroup": "MODERN STACK",
        "postedAt": "2026-09-14T02:08:27.611Z",
        "type": "fixed",
        "budget": "10.00",
        "budgetFixed": 10.0,
        "rateHourlyMid": None,
        "duration": "Less than 1 month",
        "proposals": 16,
        "clientCountry": "United States",
        "paymentVerified": True,
        "clientSpend": "$25,764.06",
        "clientSpendNum": 25764.06,
        "clientHireRate": None,
        "clientRating": 4.99,
        "experienceLevel": "intermediate",
        "skills": ["Next.js", "AI App Development", "React", "Python"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099310410198754909",
        "title": "Create an AI Vibe Coding Video Editor or Agentic Video Editor SaaS",
        "matchedKeyword": ["vibe coding", "AI web development"],
        "keywordGroup": "AI / VIBE CODING",
        "postedAt": "2026-09-14T01:34:25.831Z",
        "type": "fixed",
        "budget": "10.00",
        "budgetFixed": 10.0,
        "rateHourlyMid": None,
        "duration": "More than 6 months",
        "proposals": 1,
        "clientCountry": "Bangladesh",
        "paymentVerified": True,
        "clientSpend": "$347.25",
        "clientSpendNum": 347.25,
        "clientHireRate": None,
        "clientRating": 4.56,
        "experienceLevel": "intermediate",
        "skills": ["AI Agent Development", "AI App Development", "Vibe Coding"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099310853276640861",
        "title": "Complete E-Commerce Website Development",
        "matchedKeyword": ["ecommerce website", "ecommerce developer", "website development"],
        "keywordGroup": "ECOMMERCE",
        "postedAt": "2026-09-14T02:20:56.517Z",
        "type": "hourly",
        "budget": "20.00–40.00/hr",
        "budgetFixed": None,
        "rateHourlyMid": 30.0,
        "duration": "More than 6 months",
        "proposals": 20,
        "clientCountry": "United States",
        "paymentVerified": True,
        "clientSpend": "$29,115.78",
        "clientSpendNum": 29115.78,
        "clientHireRate": None,
        "clientRating": 4.63,
        "experienceLevel": "expert",
        "skills": ["Ecommerce Website Development", "Shopify Website Redesign"],
    },
]

known = set()
for line in JOBS.read_text().splitlines():
    if line.strip():
        known.add(json.loads(line)["url"].split("?")[0])

with JOBS.open("a") as f:
    for j in NEW:
        u = j["url"].split("?")[0]
        if u in known:
            continue
        f.write(json.dumps(j) + "\n")
        known.add(u)

print("appended", len(NEW))
