#!/usr/bin/env python3
"""Append Sept 18 live MCP jobs into jobs.jsonl (run 12)."""
import json
from pathlib import Path

ROOT = Path(__file__).parent
JOBS = ROOT / "jobs.jsonl"
STATE = ROOT / "state.json"

LIVE = [
    {
        "url": "https://www.upwork.com/jobs/~022100960468290648950",
        "title": "CMS-Based Real Estate Construction Website",
        "matchedKeyword": ["wordpress website", "wordpress development", "web development"],
        "keywordGroup": "WORDPRESS",
        "postedAt": "2026-09-18T14:50:42.570Z",
        "type": "hourly",
        "budget": None,
        "budgetFixed": None,
        "rateHourlyMid": None,
        "duration": "1 to 3 months",
        "proposals": None,
        "clientCountry": "United States",
        "paymentVerified": True,
        "clientSpend": None,
        "clientSpendNum": None,
        "clientHireRate": None,
        "clientRating": None,
        "experienceLevel": "intermediate",
        "skills": ["Web Development", "WordPress", "Search Engine Optimization", "Web Design"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022100960079383996120",
        "title": "WordPress Woo Dev",
        "matchedKeyword": ["wordpress developer", "woocommerce", "wordpress"],
        "keywordGroup": "WORDPRESS",
        "postedAt": "2026-09-18T14:49:40.192Z",
        "type": "hourly",
        "budget": None,
        "budgetFixed": None,
        "rateHourlyMid": None,
        "duration": "Less than 1 month",
        "proposals": 3,
        "clientCountry": "USA",
        "paymentVerified": True,
        "clientSpend": "$592.76",
        "clientSpendNum": 592.76,
        "clientHireRate": None,
        "clientRating": None,
        "experienceLevel": "intermediate",
        "skills": ["WordPress", "WooCommerce", "Elementor"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022100959565588347766",
        "title": "WordPress Developer Needed to Build 6-Page Microsite Within Existing Website",
        "matchedKeyword": ["web development", "wordpress developer", "wordpress website"],
        "keywordGroup": "WORDPRESS",
        "postedAt": "2026-09-18T14:47:43.917Z",
        "type": "fixed",
        "budget": "100.00",
        "budgetFixed": 100.0,
        "rateHourlyMid": None,
        "duration": "Less than 1 month",
        "proposals": 3,
        "clientCountry": "Netherlands Antilles",
        "paymentVerified": True,
        "clientSpend": "$16,755.85",
        "clientSpendNum": 16755.85,
        "clientHireRate": None,
        "clientRating": 4.99,
        "experienceLevel": "intermediate",
        "skills": ["WordPress Development", "WordPress Website"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022100957941684095274",
        "title": "GoHighLevel AI Studio (React) Developer to Fix Responsive Form Layout Glitches",
        "matchedKeyword": ["vibe coding", "gohighlevel developer", "GHL", "web development"],
        "keywordGroup": "GOHIGHLEVEL",
        "postedAt": "2026-09-18T14:40:24.637Z",
        "type": "hourly",
        "budget": None,
        "budgetFixed": None,
        "rateHourlyMid": None,
        "duration": "Less than 1 month",
        "proposals": 12,
        "clientCountry": "Australia",
        "paymentVerified": True,
        "clientSpend": "$1,095.75",
        "clientSpendNum": 1095.75,
        "clientHireRate": None,
        "clientRating": 5.0,
        "experienceLevel": "expert",
        "skills": ["HighLevel", "React", "Tailwind CSS"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022100952399750982876",
        "title": "Experienced WordPress/WooCommerce Developer for Premium E-Commerce Website",
        "matchedKeyword": ["woocommerce", "wordpress development", "ecommerce developer"],
        "keywordGroup": "WORDPRESS",
        "postedAt": "2026-09-18T14:18:16.834Z",
        "type": "fixed",
        "budget": "800.00",
        "budgetFixed": 800.0,
        "rateHourlyMid": None,
        "duration": "1 to 3 months",
        "proposals": 7,
        "clientCountry": "Nigeria",
        "paymentVerified": False,
        "clientSpend": None,
        "clientSpendNum": None,
        "clientHireRate": None,
        "clientRating": None,
        "experienceLevel": "expert",
        "skills": ["WooCommerce", "WordPress"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022100952115393626393",
        "title": "Complex Wordpress mega menu",
        "matchedKeyword": ["elementor developer", "wordpress developer"],
        "keywordGroup": "WORDPRESS",
        "postedAt": "2026-09-18T14:17:27.810Z",
        "type": "hourly",
        "budget": "40.00–60.00/hr",
        "budgetFixed": None,
        "rateHourlyMid": 50.0,
        "duration": "1 to 3 months",
        "proposals": 50,
        "clientCountry": "United Kingdom",
        "paymentVerified": True,
        "clientSpend": "$83,793.86",
        "clientSpendNum": 83793.86,
        "clientHireRate": None,
        "clientRating": 4.8,
        "experienceLevel": "expert",
        "skills": ["WordPress Customization", "WordPress Development"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022100953149191164894",
        "title": "Virtual Assistant and Marketing Support",
        "matchedKeyword": ["gohighlevel", "go high level", "gohighlevel automation"],
        "keywordGroup": "GOHIGHLEVEL",
        "postedAt": "2026-09-18T14:25:40.555Z",
        "type": "hourly",
        "budget": "6.00–6.00/hr",
        "budgetFixed": None,
        "rateHourlyMid": 6.0,
        "duration": "3 to 6 months",
        "proposals": 7,
        "clientCountry": "USA",
        "paymentVerified": True,
        "clientSpend": "$2,798.51",
        "clientSpendNum": 2798.51,
        "clientHireRate": None,
        "clientRating": 5.0,
        "experienceLevel": "intermediate",
        "skills": ["HighLevel", "CRM Automation"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022100903224536164265",
        "title": "Next.js & Supabase Developer for SaaS Feature Build",
        "matchedKeyword": ["nextjs developer", "supabase developer", "full stack developer"],
        "keywordGroup": "MODERN STACK",
        "postedAt": "2026-09-18T14:03:40.819Z",
        "type": "fixed",
        "budget": "15.00",
        "budgetFixed": 15.0,
        "rateHourlyMid": None,
        "duration": "Less than 1 month",
        "proposals": 17,
        "clientCountry": "United States",
        "paymentVerified": True,
        "clientSpend": "$3,898.53",
        "clientSpendNum": 3898.53,
        "clientHireRate": None,
        "clientRating": 4.99,
        "experienceLevel": "intermediate",
        "skills": ["Next.js", "Supabase", "Vercel", "Tailwind CSS"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022100910903405802848",
        "title": "Bubble.io Developer to Take Over Ongoing Development on Existing SaaS App",
        "matchedKeyword": ["bubble developer"],
        "keywordGroup": "ADJACENT PLATFORMS",
        "postedAt": "2026-09-18T14:33:46.370Z",
        "type": "fixed",
        "budget": "10.00",
        "budgetFixed": 10.0,
        "rateHourlyMid": None,
        "duration": "1 to 3 months",
        "proposals": 3,
        "clientCountry": "Nigeria",
        "paymentVerified": True,
        "clientSpend": "$82.38",
        "clientSpendNum": 82.38,
        "clientHireRate": None,
        "clientRating": 5.0,
        "experienceLevel": "intermediate",
        "skills": ["Bubble.io", "SaaS Development"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022100950879791682526",
        "title": "Build a WIX website",
        "matchedKeyword": ["wix website", "custom website"],
        "keywordGroup": "ADJACENT PLATFORMS",
        "postedAt": "2026-09-18T14:13:08.115Z",
        "type": "hourly",
        "budget": "15.00–30.00/hr",
        "budgetFixed": None,
        "rateHourlyMid": 22.5,
        "duration": "1 to 3 months",
        "proposals": 35,
        "clientCountry": "USA",
        "paymentVerified": True,
        "clientSpend": "$169.24",
        "clientSpendNum": 169.24,
        "clientHireRate": None,
        "clientRating": None,
        "experienceLevel": "intermediate",
        "skills": ["Wix", "Custom Web Design"],
    },
]


def norm(u: str) -> str:
    return u.split("?")[0].rstrip("/")


def main() -> None:
    known = set()
    if JOBS.exists():
        for line in JOBS.read_text().splitlines():
            if line.strip():
                known.add(norm(json.loads(line)["url"]))
    added = 0
    with JOBS.open("a") as f:
        for j in LIVE:
            u = norm(j["url"])
            if u in known:
                continue
            f.write(json.dumps(j) + "\n")
            known.add(u)
            added += 1
    print(json.dumps({"added": added}))


if __name__ == "__main__":
    main()
