#!/usr/bin/env python3
"""Bootstrap first run jobs from hourly harvest (2h window)."""
import json
from pathlib import Path

JOBS = [
  {"url":"https://www.upwork.com/jobs/~022101801150735596406","title":"Senior Technical SEO Consultant","matchedKeyword":["wordpress speed optimization","technical SEO website","website audit"],"keywordGroup":"CONVERSION / PERFORMANCE","postedAt":"2026-09-20T22:30:43.423Z","type":"hourly","budget":None,"hourlyRate":None,"duration":"More than 6 months","proposals":"5 to 10","clientCountry":"AUS","paymentVerified":True,"clientSpend":"$600.00","clientHireRate":None,"clientRating":None,"experienceLevel":"expert","skills":["Search Engine Optimization","SEO Audit","SEO Keyword Research","WordPress"]},
  {"url":"https://www.upwork.com/jobs/~022101798110940895850","title":"Web Designer & Developer – Shopify, Responsive Design & SEO","matchedKeyword":["web development","website development","web developer","web design","responsive web design","shopify developer"],"keywordGroup":"CORE WEB DEVELOPMENT","postedAt":"2026-09-20T22:18:55.717Z","type":"hourly","budget":None,"hourlyRate":"5.00–9.00/hr","duration":"More than 6 months","proposals":"10 to 15","clientCountry":"Spain","paymentVerified":True,"clientSpend":"$10,310.57","clientHireRate":None,"clientRating":4.36,"experienceLevel":"intermediate","skills":["Web Design","HTML5","HTML","Web Development"]},
  {"url":"https://www.upwork.com/jobs/~022101795824775818460","title":"GHL - Go High Level - GoHighLevel - Purple Squirrel Consulting AI Website Blueprint","matchedKeyword":["gohighlevel","go high level","GHL","gohighlevel developer","gohighlevel website","custom website","web development"],"keywordGroup":"GOHIGHLEVEL","postedAt":"2026-09-20T22:10:34.474Z","type":"hourly","budget":None,"hourlyRate":None,"duration":"1 to 3 months","proposals":"20 to 50","clientCountry":"USA","paymentVerified":True,"clientSpend":"$471.00","clientHireRate":None,"clientRating":None,"experienceLevel":"intermediate","skills":["Sales Funnel","Adaptive Web Design","Responsive Design","Web Development","HighLevel"]},
  {"url":"https://www.upwork.com/jobs/~022101747424924786051","title":"E-commerce Frontend Developer – WooCommerce to ikas Migration / Custom Storefront","matchedKeyword":["woocommerce","woocommerce developer","ecommerce developer","web developer","wordpress"],"keywordGroup":"ECOMMERCE","postedAt":"2026-09-20T21:58:21.934Z","type":"hourly","budget":None,"hourlyRate":None,"duration":"1 to 3 months","proposals":"Fewer than 5","clientCountry":"Turkey","paymentVerified":True,"clientSpend":None,"clientHireRate":None,"clientRating":None,"experienceLevel":"expert","skills":["WordPress","CSS","JavaScript","Ecommerce Website Development","Web Development"]},
  {"url":"https://www.upwork.com/jobs/~022101791137334914268","title":"Printing Service Ecommerce Website","matchedKeyword":["ecommerce website","custom website","website design"],"keywordGroup":"ECOMMERCE","postedAt":"2026-09-20T21:52:05.690Z","type":"fixed","budget":"150.00","hourlyRate":None,"duration":"1 to 3 months","proposals":"Fewer than 5","clientCountry":"Canada","paymentVerified":False,"clientSpend":None,"clientHireRate":None,"clientRating":None,"experienceLevel":"intermediate","skills":["Web Design","Graphic Design","Logo Design","Adobe Photoshop"]},
  {"url":"https://www.upwork.com/jobs/~022101789845729566083","title":"Web Developer for Business Websites","matchedKeyword":["web developer","website maintenance","ongoing web developer","wordpress maintenance"],"keywordGroup":"MAINTENANCE / RETAINERS","postedAt":"2026-09-20T21:46:29.182Z","type":"hourly","budget":None,"hourlyRate":"3.00–25.00/hr","duration":"More than 6 months","proposals":"15 to 20","clientCountry":"Canada","paymentVerified":True,"clientSpend":None,"clientHireRate":None,"clientRating":None,"experienceLevel":"entry_level","skills":["Web Development","Web Design","WordPress","HTML","Website Builder"]},
  {"url":"https://www.upwork.com/jobs/~022101789436343220579","title":"WooCommerce Developer Needed for Cosmetics Website","matchedKeyword":["woocommerce","woocommerce developer","wordpress developer"],"keywordGroup":"WORDPRESS","postedAt":"2026-09-20T21:45:14.103Z","type":"hourly","budget":None,"hourlyRate":"12.00–27.00/hr","duration":"1 to 3 months","proposals":"5 to 10","clientCountry":"Germany","paymentVerified":True,"clientSpend":None,"clientHireRate":None,"clientRating":None,"experienceLevel":"intermediate","skills":["WordPress","WooCommerce","Web Development","PHP"]},
  {"url":"https://www.upwork.com/jobs/~022101785379979334622","title":"Webflow Developer Needed – Website Build & Customization","matchedKeyword":["webflow","webflow developer","webflow website","figma to webflow","framer"],"keywordGroup":"WEBFLOW / FRAMER","postedAt":"2026-09-20T21:29:01.535Z","type":"fixed","budget":"100.00","hourlyRate":None,"duration":"1 to 3 months","proposals":"5 to 10","clientCountry":"Pakistan","paymentVerified":True,"clientSpend":"$8,235.00","clientHireRate":None,"clientRating":5,"experienceLevel":"expert","skills":["Figma","Webflow","Framer","Web Development","GSAP"]},
  {"url":"https://www.upwork.com/jobs/~022101781778628285406","title":"Senior WordPress Developer – Custom Development, ACF, Divi & Elementor","matchedKeyword":["wordpress developer","elementor developer","wordpress customization"],"keywordGroup":"WORDPRESS","postedAt":"2026-09-20T21:14:20.684Z","type":"fixed","budget":"20.00","hourlyRate":None,"duration":"Less than 1 month","proposals":"5 to 10","clientCountry":"USA","paymentVerified":True,"clientSpend":"$822.31","clientHireRate":None,"clientRating":5,"experienceLevel":"intermediate","skills":["WordPress Development","Elementor","WordPress Customization"]},
  {"url":"https://www.upwork.com/jobs/~022101780095214280067","title":"GoHighLevel Website Fulfillment Specialist – Web Development + SEO","matchedKeyword":["gohighlevel developer","gohighlevel website"],"keywordGroup":"GOHIGHLEVEL","postedAt":"2026-09-20T21:07:56.412Z","type":"fixed","budget":"50.00","hourlyRate":None,"duration":"Less than 1 month","proposals":"Fewer than 5","clientCountry":"United States","paymentVerified":True,"clientSpend":None,"clientHireRate":None,"clientRating":None,"experienceLevel":"expert","skills":["Web Development","Search Engine Optimization","HighLevel"]},
  {"url":"https://www.upwork.com/jobs/~022101788124981492067","title":"Shopify developer fix","matchedKeyword":["shopify developer","shopify maintenance"],"keywordGroup":"ECOMMERCE","postedAt":"2026-09-20T21:40:15.729Z","type":"fixed","budget":"15.00","hourlyRate":None,"duration":"Less than 1 month","proposals":"10 to 15","clientCountry":"AUS","paymentVerified":True,"clientSpend":"$108.49","clientHireRate":None,"clientRating":5,"experienceLevel":"intermediate","skills":["Shopify"]},
  {"url":"https://www.upwork.com/jobs/~022101795004706462314","title":"Social Media & Marketing Virtual Assistant – Construction Company","matchedKeyword":["framer","UI UX website"],"keywordGroup":"WEBFLOW / FRAMER","postedAt":"2026-09-20T22:06:23.049Z","type":"hourly","budget":None,"hourlyRate":None,"duration":"Less than 1 month","proposals":"Fewer than 5","clientCountry":"United States","paymentVerified":False,"clientSpend":None,"clientHireRate":None,"clientRating":None,"experienceLevel":"intermediate","skills":["Framer","Web Design","Figma"]},
  {"url":"https://www.upwork.com/jobs/~022101758918168782552","title":"Expert Webflow Developer Needed for Small Website Updates","matchedKeyword":["webflow developer","figma to webflow"],"keywordGroup":"WEBFLOW / FRAMER","postedAt":"2026-09-20T19:43:28.848Z","type":"fixed","budget":"100.00","hourlyRate":None,"duration":"Less than 1 month","proposals":"10 to 15","clientCountry":"Pakistan","paymentVerified":True,"clientSpend":None,"clientHireRate":None,"clientRating":None,"experienceLevel":"expert","skills":["Webflow","Framer","Figma"]},
  {"url":"https://www.upwork.com/jobs/~022101783275245961497","title":"Loading Page Speed Optimisation","matchedKeyword":["page speed optimization","website speed optimization","core web vitals"],"keywordGroup":"CONVERSION / PERFORMANCE","postedAt":"2026-09-20T21:20:47.336Z","type":"fixed","budget":"80.00","hourlyRate":None,"duration":"Less than 1 month","proposals":"10 to 15","clientCountry":"United Kingdom","paymentVerified":True,"clientSpend":"$3,147.34","clientHireRate":None,"clientRating":4.76,"experienceLevel":"intermediate","skills":["Page Speed Optimization","HTML","JavaScript"]},
  {"url":"https://www.upwork.com/jobs/~022101728906087699422","title":"Website Maintenance and Monitoring","matchedKeyword":["website maintenance","wordpress maintenance"],"keywordGroup":"MAINTENANCE / RETAINERS","postedAt":"2026-09-20T20:44:33.502Z","type":"fixed","budget":"20.00","hourlyRate":None,"duration":"More than 6 months","proposals":"15 to 20","clientCountry":"United Kingdom","paymentVerified":True,"clientSpend":"$1,091.00","clientHireRate":None,"clientRating":4.84,"experienceLevel":"intermediate","skills":["Web Development","WordPress","PHP"]},
  {"url":"https://www.upwork.com/jobs/~022101713896500134169","title":"Fix PMPro on a Wordpress site and add FluentCRM","matchedKeyword":["wordpress developer","wordpress customization"],"keywordGroup":"WORDPRESS","postedAt":"2026-09-20T16:44:55.763Z","type":"hourly","budget":None,"hourlyRate":"8.00–15.00/hr","duration":"Less than 1 month","proposals":"Fewer than 5","clientCountry":"United Kingdom","paymentVerified":True,"clientSpend":"$549,048.86","clientHireRate":None,"clientRating":4.71,"experienceLevel":"intermediate","skills":["WordPress"]},
  {"url":"https://www.upwork.com/jobs/~022101719139155172739","title":"Lovable.dev Website Refinement Specialist","matchedKeyword":["lovable developer","lovable app","AI web development"],"keywordGroup":"AI / VIBE CODING","postedAt":"2026-09-20T17:05:46.960Z","type":"hourly","budget":None,"hourlyRate":"18.00–40.00/hr","duration":"1 to 3 months","proposals":"20 to 50","clientCountry":"United States","paymentVerified":True,"clientSpend":"$998.06","clientHireRate":None,"clientRating":5,"experienceLevel":"expert","skills":["Web Design","Web Development","HTML"]},
  {"url":"https://www.upwork.com/jobs/~022101751854528993898","title":"Senior Full-Stack Engineer (Next.js / Supabase / Stripe) — Launch-Ready Marketplace","matchedKeyword":["nextjs developer","supabase developer","full stack developer"],"keywordGroup":"MODERN STACK","postedAt":"2026-09-20T19:15:24.732Z","type":"hourly","budget":None,"hourlyRate":"15.00–35.00/hr","duration":"1 to 3 months","proposals":"20 to 50","clientCountry":"United States","paymentVerified":False,"clientSpend":None,"clientHireRate":None,"clientRating":None,"experienceLevel":"intermediate","skills":["Next.js","React","TypeScript","Supabase","Stripe"]},
  {"url":"https://www.upwork.com/jobs/~022101741974904481496","title":"Build B2B Assessment Platform + Cold Outreach + GHL + WhatsApp AI","matchedKeyword":["gohighlevel automation","AI agent integration website","gohighlevel CRM"],"keywordGroup":"GOHIGHLEVEL","postedAt":"2026-09-20T18:36:44.973Z","type":"fixed","budget":"3,000.00","hourlyRate":None,"duration":"1 to 3 months","proposals":"20 to 50","clientCountry":"SGP","paymentVerified":True,"clientSpend":"$460.00","clientHireRate":None,"clientRating":5,"experienceLevel":"expert","skills":["HighLevel","AI Automation","Web Development"]},
  {"url":"https://www.upwork.com/jobs/~022101669313016866520","title":"Framer Website Designer & Developer","matchedKeyword":["framer developer","framer website"],"keywordGroup":"WEBFLOW / FRAMER","postedAt":"2026-09-20T13:47:59.473Z","type":"fixed","budget":"5.00","hourlyRate":None,"duration":"Less than 1 month","proposals":"Fewer than 5","clientCountry":"Nigeria","paymentVerified":False,"clientSpend":None,"clientHireRate":None,"clientRating":None,"experienceLevel":"intermediate","skills":["Framer","Web Design","Web Development"]},
  {"url":"https://www.upwork.com/jobs/~022101797632979964894","title":"Meta paid ads for a real estate website platform","matchedKeyword":["website development"],"keywordGroup":"CORE WEB DEVELOPMENT","postedAt":"2026-09-20T22:17:33.303Z","type":"fixed","budget":"400.00","hourlyRate":None,"duration":"1 to 3 months","proposals":"Fewer than 5","clientCountry":"Canada","paymentVerified":True,"clientSpend":"$19,928.82","clientHireRate":None,"clientRating":4.82,"experienceLevel":"expert","skills":["Facebook Marketing","Paid Media"]},
  {"url":"https://www.upwork.com/jobs/~022101792821717069020","title":"In-House Google Ads, Google Maps & Website SEO Manager | Remote, Long-Term","matchedKeyword":["website maintenance","technical SEO website"],"keywordGroup":"CONVERSION / PERFORMANCE","postedAt":"2026-09-20T21:58:39.644Z","type":"fixed","budget":"700.00","hourlyRate":None,"duration":"3 to 6 months","proposals":"Fewer than 5","clientCountry":"United States","paymentVerified":True,"clientSpend":None,"clientHireRate":None,"clientRating":None,"experienceLevel":"intermediate","skills":["Google Ads","SEO Audit","Website Builder"]},
  {"url":"https://www.upwork.com/jobs/~022101776240238597086","title":"Shopify Designer and Developer for Luxury Vintage E-commerce","matchedKeyword":["shopify website","shopify developer","ecommerce website"],"keywordGroup":"ECOMMERCE","postedAt":"2026-09-20T20:52:48.292Z","type":"fixed","budget":"1,000.00","hourlyRate":None,"duration":"1 to 3 months","proposals":"20 to 50","clientCountry":"United States","paymentVerified":True,"clientSpend":"$7,492.89","clientHireRate":None,"clientRating":5,"experienceLevel":"expert","skills":["Shopify","Web Design","Ecommerce Website Development"]},
]

path = Path(__file__).parent / "jobs.jsonl"
with path.open("w") as f:
    for j in JOBS:
        f.write(json.dumps(j, ensure_ascii=False) + "\n")
print(f"Wrote {len(JOBS)} jobs")
