#!/usr/bin/env python3
"""Seed run 1 from live MCP snapshot (2h window). Used when batch files are incomplete."""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent

# Jobs captured from live Upwork MCP searches on 2026-09-13 ~15:35 UTC (2h window).
SNAPSHOT = [
    {
        "url": "https://www.upwork.com/jobs/~022099158781758553453",
        "title": "PrestaShop Frontend / CMS Specialist Needed to Finish Existing Ecommerce Website",
        "matchedKeyword": ["ecommerce website", "ecommerce developer", "custom website"],
        "keywordGroup": "ECOMMERCE",
        "postedAt": "2026-09-13T15:31:52.187Z",
        "type": "fixed",
        "budget": "150.00",
        "hourlyRate": None,
        "duration": "Less than 1 month",
        "proposals": None,
        "clientCountry": "United Kingdom",
        "paymentVerified": True,
        "clientSpend": "$4,605.15",
        "clientHireRate": None,
        "clientRating": 4.73,
        "experienceLevel": "intermediate",
        "skills": ["PHP", "CSS", "Stripe", "PrestaShop"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099158139175226873",
        "title": "Shopify store",
        "matchedKeyword": ["shopify website", "shopify developer", "ecommerce website"],
        "keywordGroup": "ECOMMERCE",
        "postedAt": "2026-09-13T15:29:35.674Z",
        "type": "hourly",
        "budget": None,
        "hourlyRate": None,
        "duration": "1 to 3 months",
        "proposals": 8,
        "clientCountry": "LTU",
        "paymentVerified": True,
        "clientSpend": "$2,450.38",
        "clientHireRate": None,
        "clientRating": 5,
        "experienceLevel": "expert",
        "skills": ["Shopify Website Design", "Shopify Development", "Ecommerce Website Development"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099160215961256072",
        "title": "Automation & Integration Specialist — Zapier, Make, HubSpot, Claude (Long-Term, Hourly)",
        "matchedKeyword": ["claude code developer", "AI web development"],
        "keywordGroup": "AI / VIBE CODING",
        "postedAt": "2026-09-13T15:37:09.618Z",
        "type": "hourly",
        "budget": None,
        "hourlyRate": "25.00–40.00/hr",
        "duration": "More than 6 months",
        "proposals": None,
        "clientCountry": "United States",
        "paymentVerified": True,
        "clientSpend": None,
        "clientHireRate": None,
        "clientRating": None,
        "experienceLevel": "expert",
        "skills": ["HubSpot", "Zapier", "Make.com", "Claude Skills"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099156750705413625",
        "title": "Full-Stack Developer",
        "matchedKeyword": ["full stack developer", "web development", "nextjs developer"],
        "keywordGroup": "CORE WEB DEVELOPMENT",
        "postedAt": "2026-09-13T15:23:53.944Z",
        "type": "hourly",
        "budget": None,
        "hourlyRate": "18.00–26.00/hr",
        "duration": "More than 6 months",
        "proposals": 3,
        "clientCountry": "United States",
        "paymentVerified": False,
        "clientSpend": None,
        "clientHireRate": None,
        "clientRating": None,
        "experienceLevel": "expert",
        "skills": ["Full-Stack Development", "React", "Next.js", "TypeScript"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099154953658018637",
        "title": "Front-End Developer",
        "matchedKeyword": ["frontend developer", "nextjs developer", "react developer"],
        "keywordGroup": "MODERN STACK",
        "postedAt": "2026-09-13T15:16:40.730Z",
        "type": "hourly",
        "budget": None,
        "hourlyRate": "16.00–24.00/hr",
        "duration": "More than 6 months",
        "proposals": 10,
        "clientCountry": "United States",
        "paymentVerified": False,
        "clientSpend": None,
        "clientHireRate": None,
        "clientRating": None,
        "experienceLevel": "expert",
        "skills": ["Next.js", "Tailwind CSS", "TypeScript", "React"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099146253503352313",
        "title": "Custom WordPress & WooCommerce Developer (PHP, React & Laravel)",
        "matchedKeyword": ["wordpress developer", "woocommerce", "woocommerce developer"],
        "keywordGroup": "WORDPRESS",
        "postedAt": "2026-09-13T15:15:21.408Z",
        "type": "fixed",
        "budget": "20.00",
        "hourlyRate": None,
        "duration": "1 to 3 months",
        "proposals": None,
        "clientCountry": "Pakistan",
        "paymentVerified": False,
        "clientSpend": None,
        "clientHireRate": None,
        "clientRating": None,
        "experienceLevel": "expert",
        "skills": ["WordPress", "WooCommerce", "PHP", "Laravel", "React"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099153688265861965",
        "title": "English speaking Web Designer",
        "matchedKeyword": ["web design", "website design", "framer developer"],
        "keywordGroup": "WEB DESIGN",
        "postedAt": "2026-09-13T15:11:44.378Z",
        "type": "hourly",
        "budget": None,
        "hourlyRate": None,
        "duration": "Less than 1 month",
        "proposals": 4,
        "clientCountry": "United States",
        "paymentVerified": True,
        "clientSpend": None,
        "clientHireRate": None,
        "clientRating": None,
        "experienceLevel": "intermediate",
        "skills": ["Web Design", "Framer", "Wix", "Landing Page Design"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099106923871544925",
        "title": "Looking for someone to redesign our WordPress website",
        "matchedKeyword": ["wordpress redesign", "website redesign", "wordpress"],
        "keywordGroup": "WORDPRESS",
        "postedAt": "2026-09-13T15:05:14.574Z",
        "type": "hourly",
        "budget": None,
        "hourlyRate": None,
        "duration": "Less than 1 month",
        "proposals": 1,
        "clientCountry": "Bangladesh",
        "paymentVerified": False,
        "clientSpend": None,
        "clientHireRate": None,
        "clientRating": None,
        "experienceLevel": "intermediate",
        "skills": ["WordPress", "Elementor", "WooCommerce", "Conversion Rate Optimization"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099152063478337290",
        "title": "WordPress Website",
        "matchedKeyword": ["wordpress website", "wordpress development", "technical SEO website"],
        "keywordGroup": "WORDPRESS",
        "postedAt": "2026-09-13T15:05:07.913Z",
        "type": "fixed",
        "budget": "550.00",
        "hourlyRate": None,
        "duration": "1 to 3 months",
        "proposals": 22,
        "clientCountry": "CAN",
        "paymentVerified": True,
        "clientSpend": "$925.00",
        "clientHireRate": None,
        "clientRating": 5,
        "experienceLevel": "expert",
        "skills": ["WordPress", "Web Development", "SEO Content"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099151032033291928",
        "title": "Squarespace Developer Needed Website Completion and Website Refresh",
        "matchedKeyword": ["squarespace website", "website redesign"],
        "keywordGroup": "ADJACENT PLATFORMS",
        "postedAt": "2026-09-13T15:01:02.990Z",
        "type": "fixed",
        "budget": "10.00",
        "hourlyRate": None,
        "duration": "1 to 3 months",
        "proposals": 2,
        "clientCountry": "IND",
        "paymentVerified": True,
        "clientSpend": "$906.80",
        "clientHireRate": None,
        "clientRating": 4.99,
        "experienceLevel": "intermediate",
        "skills": ["Squarespace", "Website Redesign", "Custom Web Design"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099140812387880714",
        "title": "GoHighLevel CRM Architect / Developer Needed – Real Estate Investment CRM + AI Automation",
        "matchedKeyword": ["gohighlevel developer", "gohighlevel CRM", "GHL"],
        "keywordGroup": "GOHIGHLEVEL",
        "postedAt": "2026-09-13T15:00:19.393Z",
        "type": "hourly",
        "budget": None,
        "hourlyRate": None,
        "duration": "3 to 6 months",
        "proposals": 13,
        "clientCountry": "United States",
        "paymentVerified": False,
        "clientSpend": None,
        "clientHireRate": None,
        "clientRating": None,
        "experienceLevel": "expert",
        "skills": ["AI Agent Development", "CRM Software", "Lead Generation"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099148858442878730",
        "title": "Framer Expert Needed to Repair Existing Website + Fix Tablet and Mobile Responsiveness",
        "matchedKeyword": ["framer developer", "framer website", "responsive web design"],
        "keywordGroup": "WEBFLOW / FRAMER",
        "postedAt": "2026-09-13T14:52:49.100Z",
        "type": "fixed",
        "budget": "300.00",
        "hourlyRate": None,
        "duration": "1 to 3 months",
        "proposals": 1,
        "clientCountry": "United States",
        "paymentVerified": True,
        "clientSpend": None,
        "clientHireRate": None,
        "clientRating": None,
        "experienceLevel": "intermediate",
        "skills": ["Web Design", "Website", "Web Development"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099151035285912941",
        "title": "Web developer & SEO Specialist",
        "matchedKeyword": ["web developer", "technical SEO website", "website speed optimization"],
        "keywordGroup": "CONVERSION / PERFORMANCE",
        "postedAt": "2026-09-13T15:23:23.420Z",
        "type": "hourly",
        "budget": None,
        "hourlyRate": "12.00–15.00/hr",
        "duration": "More than 6 months",
        "proposals": 2,
        "clientCountry": "United States",
        "paymentVerified": False,
        "clientSpend": None,
        "clientHireRate": None,
        "clientRating": None,
        "experienceLevel": "expert",
        "skills": ["SEO Services", "On-Page SEO"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099127295745769608",
        "title": "Full-Stack Developer Needed to Finish Existing SaaS Web Application (Lovable + Supabase)",
        "matchedKeyword": ["lovable developer", "supabase developer", "full stack developer"],
        "keywordGroup": "AI / VIBE CODING",
        "postedAt": "2026-09-13T13:26:11.001Z",
        "type": "hourly",
        "budget": None,
        "hourlyRate": None,
        "duration": "1 to 3 months",
        "proposals": 75,
        "clientCountry": "Canada",
        "paymentVerified": True,
        "clientSpend": "$2,280.38",
        "clientHireRate": None,
        "clientRating": 5,
        "experienceLevel": "intermediate",
        "skills": ["React", "TypeScript", "PostgreSQL", "Supabase"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099131682689958024",
        "title": "AI-Assisted Education Newsletter — Website",
        "matchedKeyword": ["AI web development", "AI web developer"],
        "keywordGroup": "AI / VIBE CODING",
        "postedAt": "2026-09-13T13:44:25.035Z",
        "type": "fixed",
        "budget": "1,200.00",
        "hourlyRate": None,
        "duration": "1 to 3 months",
        "proposals": 31,
        "clientCountry": "United States",
        "paymentVerified": True,
        "clientSpend": "$4,793.50",
        "clientHireRate": None,
        "clientRating": 4.86,
        "experienceLevel": "intermediate",
        "skills": ["HTML", "CSS", "Email Marketing"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099139908343085374",
        "title": "Long Term - Python and Vue Engineer for Healtech startup",
        "matchedKeyword": ["claude code developer", "AI web developer"],
        "keywordGroup": "AI / VIBE CODING",
        "postedAt": "2026-09-13T14:16:58.108Z",
        "type": "hourly",
        "budget": None,
        "hourlyRate": "15.00–35.00/hr",
        "duration": "More than 6 months",
        "proposals": 73,
        "clientCountry": "United States",
        "paymentVerified": True,
        "clientSpend": "$652,418.45",
        "clientHireRate": None,
        "clientRating": 4.93,
        "experienceLevel": "intermediate",
        "skills": ["Claude Code", "Full-Stack Development", "Django"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022098896466971797085",
        "title": "Senior Webflow CMS Developer",
        "matchedKeyword": ["webflow developer", "webflow website"],
        "keywordGroup": "WEBFLOW / FRAMER",
        "postedAt": "2026-09-13T01:09:43.190Z",
        "type": "hourly",
        "budget": None,
        "hourlyRate": "18.00–35.00/hr",
        "duration": "1 to 3 months",
        "proposals": 29,
        "clientCountry": "Germany",
        "paymentVerified": False,
        "clientSpend": None,
        "clientHireRate": None,
        "clientRating": None,
        "experienceLevel": "expert",
        "skills": ["JavaScript", "HTML5"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099095668926522973",
        "title": "Web designer for a 9-page company site (design only). Strategy/reference research complete.",
        "matchedKeyword": ["webflow", "figma to webflow", "web design"],
        "keywordGroup": "WEBFLOW / FRAMER",
        "postedAt": "2026-09-13T11:26:06.157Z",
        "type": "hourly",
        "budget": None,
        "hourlyRate": None,
        "duration": "1 to 3 months",
        "proposals": 18,
        "clientCountry": "United States",
        "paymentVerified": True,
        "clientSpend": "$14,794.12",
        "clientHireRate": None,
        "clientRating": 4.75,
        "experienceLevel": "intermediate",
        "skills": ["Webflow", "Figma to Webflow Plugin", "Web Design"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099140577507223133",
        "title": "Restaurant Web Page Redesign",
        "matchedKeyword": ["website redesign", "webflow redesign", "wix website"],
        "keywordGroup": "WEB DESIGN",
        "postedAt": "2026-09-13T14:19:00.337Z",
        "type": "hourly",
        "budget": None,
        "hourlyRate": None,
        "duration": "Less than 1 month",
        "proposals": 17,
        "clientCountry": "United States",
        "paymentVerified": False,
        "clientSpend": None,
        "clientHireRate": None,
        "clientRating": None,
        "experienceLevel": "intermediate",
        "skills": ["Webflow", "WordPress", "Wix", "Squarespace"],
    },
    {
        "url": "https://www.upwork.com/jobs/~022099048056679578989",
        "title": "WeWeb/Xano Developer Needed to Fix One API Connection",
        "matchedKeyword": ["vibe coding", "bolt developer"],
        "keywordGroup": "AI / VIBE CODING",
        "postedAt": "2026-09-13T08:11:56.083Z",
        "type": "fixed",
        "budget": "10.00",
        "hourlyRate": None,
        "duration": "Less than 1 month",
        "proposals": 6,
        "clientCountry": "United States",
        "paymentVerified": True,
        "clientSpend": "$4,032.65",
        "clientHireRate": None,
        "clientRating": 4.98,
        "experienceLevel": "expert",
        "skills": ["Vibe Coding", "No-Code Development", "WeWeb"],
    },
]


def main() -> None:
    jobs_path = ROOT / "jobs.jsonl"
    with jobs_path.open("w") as f:
        for row in SNAPSHOT:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")
    meta = {
        "attempted": json.loads((ROOT / "keywords.json").read_text()),
        "completed": [],
        "failed": [],
        "errors": [
            "Run 1 used live MCP snapshot seed; full 92-keyword batch capture continues next hourly runs"
        ],
        "seededAt": datetime.now(timezone.utc).isoformat(),
    }
    kw_list = [k["keyword"] for k in json.loads((ROOT / "keywords.json").read_text())]
    meta["attempted"] = kw_list
    meta["completed"] = list(
        {kw for job in SNAPSHOT for kw in job.get("matchedKeyword", [])}
    )
    meta["failed"] = [k for k in kw_list if k not in meta["completed"]]
    (ROOT / "run_meta.json").write_text(json.dumps(meta, indent=2))
    print(f"Seeded {len(SNAPSHOT)} jobs")


if __name__ == "__main__":
    main()
